# enconding: utf-8
require 'rubygems'
require 'bundler'
require 'thor/rake_compat'
require 'spec/rake/spectask'

Bundler.setup
Bundler.require(:default, :development)

GEM_NAME = 'psr'
EXTRA_RDOC_FILES = ["README", "LICENSE", "CHANGELOG.rdoc", "VERSION", "Thorfile"]

class Default < Thor
  include Thor::RakeCompat

  default_task :spec

  Spec::Rake::SpecTask.new(:spec) do |t|
    t.libs << 'lib'
    t.spec_opts = ['--options', "spec/spec.opts"]
    t.spec_files = FileList['spec/**/*_spec.rb']
  end

end